### ISSUE TITLE
As an SKC member I want to be able to log in to the site so that I have access to more information

### ISSUE THREAD

**Issue by TophatPigeonno** [SKC-Team11/SKCrime#4]

**Comment by Kirlovon** [comment]
Acceptance criteria:
GIVEN: As an SKC member I want to be able to log in to the site so that I have access to more personal information
WHEN: I click on login page, and I enter my data in the login form
THEN: I get more tabs on the dashboard with data available only to my account

WHEN: I click on login, and I enter invalid data to login form
THEN: I get an error with the message "Invalid authentication data"
